# PerWorldPunish - Allows per-world punishments such as ban, kick and tempban!
# Support: https://discord.gg/Scgqfm5EU4
# GitHub Source Code: https://github.com/WatermanMC/PerWorldPunish

# This will show id there is no reason provided for ban/kick/tempban
default-reason: "<red>No reason provided."

# The player will get teleported in this world after getting banned/kicked
fallback-world: 'world'